// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqz7Cmhruvpo_aOPqLqp-cCatch-I9kMs',
    appId: '1:452262326863:web:a47850d90d4d097c59f03a',
    messagingSenderId: '452262326863',
    projectId: 'prueba-mensajes-e3f92',
    authDomain: 'prueba-mensajes-e3f92.firebaseapp.com',
    storageBucket: 'prueba-mensajes-e3f92.firebasestorage.app',
    measurementId: 'G-NCYJV1MGSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAut7iUTNtg2o8XaTZ5HWCm_UjMsutm1A0',
    appId: '1:452262326863:android:d4e7e6c911933b5c59f03a',
    messagingSenderId: '452262326863',
    projectId: 'prueba-mensajes-e3f92',
    storageBucket: 'prueba-mensajes-e3f92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK47vefEhVj4U522QI9xbJJymZyA_SMSU',
    appId: '1:452262326863:ios:75da4028b0dd1bc859f03a',
    messagingSenderId: '452262326863',
    projectId: 'prueba-mensajes-e3f92',
    storageBucket: 'prueba-mensajes-e3f92.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK47vefEhVj4U522QI9xbJJymZyA_SMSU',
    appId: '1:452262326863:ios:75da4028b0dd1bc859f03a',
    messagingSenderId: '452262326863',
    projectId: 'prueba-mensajes-e3f92',
    storageBucket: 'prueba-mensajes-e3f92.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqz7Cmhruvpo_aOPqLqp-cCatch-I9kMs',
    appId: '1:452262326863:web:097b9ef14bfab5d459f03a',
    messagingSenderId: '452262326863',
    projectId: 'prueba-mensajes-e3f92',
    authDomain: 'prueba-mensajes-e3f92.firebaseapp.com',
    storageBucket: 'prueba-mensajes-e3f92.firebasestorage.app',
    measurementId: 'G-B0RVVR86F7',
  );
}
