// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuQ5Hgg9i1xxFMfJL29CwwBXhPuDa4Di4',
    appId: '1:736502517872:web:ed390c28f526e1efd3a4b5',
    messagingSenderId: '736502517872',
    projectId: 'instamess-af60b',
    authDomain: 'instamess-af60b.firebaseapp.com',
    storageBucket: 'instamess-af60b.appspot.com',
    measurementId: 'G-B9FJ5P6GPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3p2EmXrdN3Am-9zRPj2JZcbTOSVWdnfI',
    appId: '1:736502517872:android:392bcb0678e56d0fd3a4b5',
    messagingSenderId: '736502517872',
    projectId: 'instamess-af60b',
    storageBucket: 'instamess-af60b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVLEesvmD3pA7lpS3C3ki_gzrHGOFteQ4',
    appId: '1:736502517872:ios:fa500500d48984e4d3a4b5',
    messagingSenderId: '736502517872',
    projectId: 'instamess-af60b',
    storageBucket: 'instamess-af60b.appspot.com',
    iosBundleId: 'com.example.instamess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVLEesvmD3pA7lpS3C3ki_gzrHGOFteQ4',
    appId: '1:736502517872:ios:fa500500d48984e4d3a4b5',
    messagingSenderId: '736502517872',
    projectId: 'instamess-af60b',
    storageBucket: 'instamess-af60b.appspot.com',
    iosBundleId: 'com.example.instamess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuQ5Hgg9i1xxFMfJL29CwwBXhPuDa4Di4',
    appId: '1:736502517872:web:24a241a50ab122dbd3a4b5',
    messagingSenderId: '736502517872',
    projectId: 'instamess-af60b',
    authDomain: 'instamess-af60b.firebaseapp.com',
    storageBucket: 'instamess-af60b.appspot.com',
    measurementId: 'G-7SMGQB4HRF',
  );
}
